-- Indexes
CREATE UNIQUE INDEX action_logs_pkey ON public.action_logs USING btree (id);
CREATE INDEX idx_action_logs_user_action ON public.action_logs USING btree (user_id, action, created_at DESC);
CREATE UNIQUE INDEX deletion_capacity_pkey ON public.deletion_capacity USING btree (day);
CREATE UNIQUE INDEX email_sends_pkey ON public.email_sends USING btree (id);
CREATE INDEX idx_email_sends_user_type_sent_at ON public.email_sends USING btree (user_id, type, sent_at);
CREATE INDEX idx_email_sends_user_type_time ON public.email_sends USING btree (user_id, type, sent_at DESC);
CREATE INDEX idx_magic_links_active ON public.magic_links USING btree (token) WHERE (is_active = true);
CREATE INDEX idx_magic_links_type_token ON public.magic_links USING btree (type, token);
CREATE INDEX idx_magic_links_unused ON public.magic_links USING btree (token) WHERE (used = false);
CREATE INDEX idx_magic_links_user_type_active ON public.magic_links USING btree (user_id, type, is_active);
CREATE UNIQUE INDEX magic_links_pkey ON public.magic_links USING btree (id);
CREATE UNIQUE INDEX magic_links_token_key ON public.magic_links USING btree (token);
CREATE INDEX idx_refresh_token_token ON public.refresh_tokens USING btree (token);
CREATE INDEX idx_refresh_tokens_user_revoked ON public.refresh_tokens USING btree (user_id, revoked);
CREATE UNIQUE INDEX refresh_tokens_pkey ON public.refresh_tokens USING btree (id);
CREATE UNIQUE INDEX refresh_tokens_token_unique ON public.refresh_tokens USING btree (token);
CREATE UNIQUE INDEX user_deletion_cycles_pkey ON public.user_deletion_cycles USING btree (user_id);
CREATE INDEX idx_user_deletions_scheduled_date ON public.user_deletions USING btree (scheduled_date);
CREATE INDEX idx_user_deletions_status_date ON public.user_deletions USING btree (status, scheduled_date);
CREATE UNIQUE INDEX user_deletions_pkey ON public.user_deletions USING btree (id);
CREATE UNIQUE INDEX user_deletions_recovery_token_key ON public.user_deletions USING btree (recovery_token);
CREATE UNIQUE INDEX user_deletions_token_key ON public.user_deletions USING btree (token);
CREATE UNIQUE INDEX user_logins_pkey ON public.user_logins USING btree (id);
CREATE INDEX idx_users_deleted_at ON public.users USING btree (deleted_at);
CREATE INDEX idx_users_email_lower ON public.users USING btree (lower(email));
CREATE INDEX idx_users_is_email_verified ON public.users USING btree (is_email_verified);
CREATE UNIQUE INDEX users_email_key ON public.users USING btree (email);
CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);