// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthResponse struct {
	User         *User  `json:"user"`
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type DeleteAccountInput struct {
	UserID string `json:"userID"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RecoverAccountInput struct {
	Token       string `json:"token"`
	NewPassword string `json:"newPassword"`
}

type RecoverPasswordInput struct {
	Email string `json:"email"`
}

type RegisterUserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	ID              string  `json:"id"`
	Name            string  `json:"name"`
	Email           string  `json:"email"`
	CreatedAt       string  `json:"createdAt"`
	UpdatedAt       string  `json:"updatedAt"`
	IsEmailVerified bool    `json:"isEmailVerified"`
	DeletedAt       *string `json:"deletedAt,omitempty"`
	AvatarURL       *string `json:"avatarURL,omitempty"`
	DeletionDueAt   *string `json:"deletionDueAt,omitempty"`
	LastLoginAt     *string `json:"lastLoginAt,omitempty"`
	IsDeleted       bool    `json:"isDeleted"`
}
